# Secret pour la clé JWT
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: development
type: Opaque
data:
  JWT_SECRET: c2VjcmV0a2V5MTIz  # "secretkey123" encodé en base64 (à remplacer par une clé sécurisée)