workflow:
    name: Services auth-service Pipeline  # Nom personnalisé du pipeline
    rules:
        - if: $CI_COMMIT_BRANCH == 'main' || $CI_COMMIT_BRANCH =~ /^dev/
          when: always
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^dev/ && $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: always 
        - when: never  # Par défaut, ne rien exécuter


stages:
  - build
  - test
  - sast
  - sca
  - docker-build
  - trivy-scan
  - docker-push


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTEST_ADDOPTS: "--junitxml=report.xml"

  # Nexus configuration
  NEXUS_USER: "admin"  # 👤 Nom d'utilisateur pour l'authentification à Nexus
  NEXUS_PRIVATE: "nexus.tubie.devops.ops:8083"  # 🌍 Nom DNS ou IP du serveur Nexus

  # Docker Configuration
  IMAGE_VERSION: $CI_PIPELINE_ID 
  IMAGE_NAME: "gateway-svc"
  DOCKER_REGISTRY: "${NEXUS_PRIVATE}"
  DOCKER_IMAGE: "${DOCKER_REGISTRY}/${IMAGE_NAME}"
  

# ===== STAGE: BUILD =====
build:
  image: python:3.12
  stage: build
  # Cache global pour éviter la duplication
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends libssl-dev openssl ca-certificates build-essential gcc python3-dev
    - python -V 
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip
  script: 
    - pip install -r requirements.txt


# ===== STAGE: TEST =====
test:
  image: python:3.12
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends libssl-dev openssl ca-certificates build-essential gcc python3-dev
    - python -V 
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt pytest pytest-cov
  script: 
    - pytest tests/ --verbose --cov=. --cov-report=xml:coverage.xml
  artifacts:
    when: always
    paths:
      - report.xml
      - coverage.xml
    reports:
      junit: report.xml
    expire_in: 1 week  


# ===== STAGE: SONARQUBE - Analyse avancée =====
sonarqube-check:
  stage: sast
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Définit l'emplacement du cache des tâches d'analyse
    GIT_DEPTH: "0"  # Indique à git de récupérer toutes les branches du projet, requises par la tâche d'analyse  
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .sonar/cache
  needs:
    - test
  script:
    - sonar-scanner
        -Dsonar.projectKey="gateway-service"
        -Dsonar.projectName="Gateway-service"
        -Dsonar.projectVersion=1.0
        -Dsonar.sources=.
        -Dsonar.host.url="$SONAR_HOST_URL"
        -Dsonar.login="$SONAR_TOKEN"
        -Dsonar.python.version=3.11
        -Dsonar.python.coverage.reportPaths=report.xml
        -Dsonar.qualitygate.wait=true
  allow_failure: false  # Stop le pipeline si l'analyse échoue


# ===== STAGE: SNYK - Scan des dépendances =====
snyk-dependency-scan:
  stage: sca
  image: node:20-slim
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
      - .venv/lib/
  before_script:
    - apt-get update && apt-get install -y python3 python3-pip python3-venv
    - npm install -g snyk
    - python3 -V 
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - snyk auth "$SNYK_TOKEN"
    - snyk test --file=requirements.txt --severity-threshold=high --json-file-output=snyk_report.json || echo "Snyk a trouvé des vulnérabilités mais on continue le pipeline"
    - snyk monitor --file=requirements.txt
  artifacts:
    when: always
    paths:
      - snyk_report.json
    reports:
      sast: snyk_report.json  # Intégration avec GitLab Security Dashboard
    expire_in: 1 week
  allow_failure: true


# ===== STAGE: DOCKER BUILD =====
docker_build:
  stage: docker-build
  image: docker:latest
  dependencies: []
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "Construction de l'image Docker..."
    - docker build -t "$DOCKER_IMAGE:$IMAGE_VERSION" .
    - docker images "$DOCKER_IMAGE:$IMAGE_VERSION"
    - mkdir image
    - docker save "$DOCKER_IMAGE:$IMAGE_VERSION" > "image/gateway-svc-$IMAGE_VERSION.tar"
    - docker rmi "$DOCKER_IMAGE:$IMAGE_VERSION"
  artifacts:
    paths:
      - image/
    when: on_success
    expire_in: 1 week


# ===== STAGE: TRIVY =====
trivy_scan:
  stage: trivy-scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  needs: 
    - docker_build
  script:
    - trivy image 
      --severity CRITICAL,HIGH 
      --ignore-unfixed --exit-code 1
      --input "image/gateway-svc-$IMAGE_VERSION.tar"
      --format cyclonedx --output trivy-report.json
  artifacts:
    reports:
      cyclonedx: trivy-report.json  # Intégration avec GitLab Security
    paths:
      - trivy-report.json
  allow_failure: false  # Bloquer si vulnérabilités critiques  


# ===== STAGE: DOCKER PUSH =====
docker_push: 
  stage: docker-push
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  needs:
    - docker_build
    - trivy_scan  # S'exécute seulement si Trivy réussit
  before_script:
    # Charger image depuis les artefacts
    - docker load -i "image/gateway-svc-$IMAGE_VERSION.tar"
  script:
    - echo "Publication de l'image Docker vers Nexus..."
    - echo "$NEXUS_PASSWORD" | docker login "$NEXUS_PRIVATE" -u "$NEXUS_USER" --password-stdin
    - docker tag "$DOCKER_IMAGE:$IMAGE_VERSION" "$NEXUS_PRIVATE/tubie-ops/gateway-svc:$IMAGE_VERSION"
    - docker push "$NEXUS_PRIVATE/tubie-ops/gateway-svc:$IMAGE_VERSION"  
    - docker rmi "$NEXUS_PRIVATE/tubie-ops/gateway-svc:$IMAGE_VERSION" || true  
  